export const SET_TITLE = 'SET_TITLE'
export const PUSH_TITLE_TO_HISTORY = 'PUSH_TITLE_TO_HISTORY'
export const POP_LAST_SAVED_TITLE = 'POP_LAST_SAVED_TITLE'

export const SET_LEFT_HEADER_BUTTONS = 'SET_LEFT_HEADER_BUTTONS'
export const SET_RIGHT_HEADER_BUTTONS = 'SET_RIGHT_HEADER_BUTTONS'
